# sops-nix configuration
# https://github.com/Mic92/sops-nix
#
# This file defines which age keys can decrypt which secrets.
# Each host's key is derived from its SSH host key.
#
# To get a host's age public key, run on that host:
#   nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
#
# To edit secrets from any host:
#   SOPS_AGE_SSH_KEY=/etc/ssh/ssh_host_ed25519_key sops secrets.yaml

keys:
  # Host keys - any of these machines can decrypt and edit secrets
  # Run on each host: nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
  # After adding the key, run: sops updatekeys secrets.yaml
  - &rustbucket age1etlt2mmk4w6jvn600mdf96ve9jdv8gc8lj8ua8vxz9cf9duprsqsfcrm66
  - &michael-rustbucket age1hm54wehtm6vt8vvmlx8dj7lnxmaqg8eu3wkp9q5343xtj9k5lg7q92cpk0
  - &claptrap age1lkcjrcmfrvrg7s0njcs20lvsermmd7mv7093t9lma4pk7zfqaulsnh4nnl

creation_rules:
  - path_regex: \.yaml$
    key_groups:
      - age:
          - *rustbucket
          - *michael-rustbucket
          - *claptrap
