{
  inputs,
  ...
}:
{
  # Niri Session Manager - persistent window sessions
  # https://github.com/MTeaHead/niri-session-manager
  #
  # Automatically saves window layout periodically and restores on startup.
  # Session data stored in ~/.local/share/niri-session-manager/
  # Config file in ~/.config/niri-session-manager/config.toml

  flake.modules.nixos.niri-session-manager =
    { ... }:
    {
      imports = [ inputs.niri-session-manager.nixosModules.niri-session-manager ];

      # Enable the systemd user service
      services.niri-session-manager.enable = true;
    };

  # Home Manager module for niri-session-manager configuration
  # Creates ~/.config/niri-session-manager/config.toml
  flake.modules.homeManager.niri-session-manager =
    { config, lib, ... }:
    let
      cfg = config.programs.niri.session-manager;
    in
    {
      options.programs.niri.session-manager = {
        enable = lib.mkEnableOption "niri-session-manager user configuration" // {
          default = true;
        };

        singleInstanceApps = lib.mkOption {
          type = lib.types.listOf lib.types.str;
          default = [ ];
          example = [ "firefox" "zen" ];
          description = "Apps that should only have one instance.";
        };

        skipApps = lib.mkOption {
          type = lib.types.listOf lib.types.str;
          default = [ ];
          example = [ "discord" "slack" ];
          description = "Applications to skip during startup.";
        };

        appMappings = lib.mkOption {
          type = lib.types.attrsOf (lib.types.listOf lib.types.str);
          default = { };
          example = {
            "com.mitchellh.ghostty" = [ "ghostty" ];
            "vesktop" = [ "flatpak" "run" "dev.vencord.Vesktop" ];
          };
          description = "Map app IDs to custom launch commands.";
        };
      };

      config = lib.mkIf cfg.enable {
        xdg.configFile."niri-session-manager/config.toml".text = ''
          # Niri Session Manager Configuration
          # Generated by Home Manager

          [single_instance_apps]
          apps = [${lib.concatMapStringsSep ", " (app: ''"${app}"'') cfg.singleInstanceApps}]

          [skip_apps]
          apps = [${lib.concatMapStringsSep ", " (app: ''"${app}"'') cfg.skipApps}]

          [app_mappings]
          ${lib.concatStringsSep "\n" (lib.mapAttrsToList (
            appId: cmd: ''"${appId}" = [${lib.concatMapStringsSep ", " (c: ''"${c}"'') cmd}]''
          ) cfg.appMappings)}
        '';
      };
    };
}
